const fixedData =
{
    url: "https://drive.google.com/uc?id=",
    author: "Arnaud De Baerdemaeker",
    camera: "Sony Cybershot DSC-HX300",
    phone: "Sony Xperia Z",
    belgium: "Belgique",
    france: "France",
    aperture: "Ouverture : ",
    shutter_speed: "Vitesse d'obturation : ",
    focal_length: "Distance focale : ",
    iso: "ISO : "
}


const photos2014 =
[
    {
        title: 2014
    },
    {
        full_image: fixedData.url + "1VaHBP5cXEeCB7gHivW9J54Xl3atdJAXM",
        thumbnail: fixedData.url + "1FngJTHyYW4L07yL4UGMernAaaqQQsS42",
        author: fixedData.author,
        name: "Le Tapis de Fleurs",
        place: "Bruxelles, " + fixedData.belgium,
        day: "Jeudi",
        date: 14 + " août " + 2014,
        time: "15:39",
        aperture: fixedData.aperture + "f/" + 3.2,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 640 + " s",
        focal_length: fixedData.focal_length + 4.3 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1MlqQ2bGfDF3TrSoYf9QmU-Kl0pmzFudP",
        thumbnail: fixedData.url + "1Yliry21i60r_j9unkuTYa0D1TyQUOmOs",
        author: fixedData.author,
        name: "Le Tapis de Fleurs",
        place: "Bruxelles, " + fixedData.belgium,
        day: "Jeudi",
        date: 14 + " août " + 2014,
        time: "16:11",
        aperture: fixedData.aperture + "f/" + 3.2,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 800 + " s",
        focal_length: fixedData.focal_length + 4.3 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1ZapRpyKe7lu5pQ6LCOUbDY0l4e4T_Qoq",
        thumbnail: fixedData.url + "1PjglNUjMPZ0LiBlOW_aJCUkPx7eNdFY6",
        author: fixedData.author,
        name: "L'Atomium",
        place: "Laeken, " + fixedData.belgium,
        day: "Mercredi",
        date: 17 + " septembre " + 2014,
        time: "13:10",
        aperture: fixedData.aperture + "f/" + 2.4,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 1000 + " s",
        focal_length: fixedData.focal_length + 4.1 + " mm",
        iso: fixedData.iso + 40,
        camera: fixedData.phone
    },
    {
        full_image: fixedData.url + "1fXXmmx4lZoC3KLfyVlgJDgq2nCA736ot",
        thumbnail: fixedData.url + "1BaTBz5JP7mwB1vdghXlb5BtMd-tPRyn_",
        author: fixedData.author,
        name: "L'Atomium",
        place: "Laeken, " + fixedData.belgium,
        day: "Mercredi",
        date: 17 + " septembre " + 2014,
        time: "13:36",
        aperture: fixedData.aperture + "f/" + 2.4,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 1000 + " s",
        focal_length: fixedData.focal_length + 4.1 + " mm",
        iso: fixedData.iso + 40,
        camera: fixedData.phone
    },
    {
        full_image: fixedData.url + "1ErOVGOS0wddbAN8oRExZdCOpt3mjGPX3",
        thumbnail: fixedData.url + "1X5bAM2WtrpQP2EC5GRPSRe0-nzYKc-Ku",
        author: fixedData.author,
        name: "L'Atomium",
        place: "Laeken, " + fixedData.belgium,
        day: "Mercredi",
        date: 17 + " septembre " + 2014,
        time: "13:39",
        aperture: fixedData.aperture + "f/" + 2.4,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 1000 + " s",
        focal_length: fixedData.focal_length + 4.1 + " mm",
        iso: fixedData.iso + 40,
        camera: fixedData.phone
    }
];

const photos2015 =
[
    {
        title: 2015
    },
    {
        full_image: fixedData.url + "10qp__SlDPvUtN_QFXAmxlST3AewybqeZ",
        thumbnail: fixedData.url + "1cNj8fqVrLnoDzyUC5fPJ2OGE0WC4nYkA",
        author: fixedData.author,
        name: "L'Hôtel de ville de Paris",
        place: "Paris, " + fixedData.france,
        day: "Mercredi",
        date: 27 + " mai " + 2015,
        time: "17:38",
        aperture: fixedData.aperture + "f/" + 3.2,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 1600 + " s",
        focal_length: fixedData.focal_length + 7.1 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1i1bd-Y9QJoeAVAEy_7btOFwWue8anrvb",
        thumbnail: fixedData.url + "1kcGf9CGJ82-pKPps3uBCrdJGgYFbIiZ6",
        author: fixedData.author,
        name: "La Place Bellecour",
        place: "Lyon, " + fixedData.france,
        day: "Samedi",
        date: 30 + " mai " + 2015,
        time: "13:10",
        aperture: fixedData.aperture + "f/" + 4.5,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 250 + " s",
        focal_length: fixedData.focal_length + 29.4 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    }
];

const photos2016 =
[
    {
        title: 2016
    },
    {
        full_image: fixedData.url + "1p0NZkKgZO5Y2z7NRhZ4Df33ORh3nRd0Q",
        thumbnail: fixedData.url + "1E7yZKEU2g1ZtFf2vPLa2Z-H2NG_DWWIJ",
        author: fixedData.author,
        name: "Parc de la Boverie",
        place: "Liège, " + fixedData.belgium,
        day: "Vendredi",
        date: 13 + " mai " + 2016,
        time: "10:59",
        aperture: fixedData.aperture + "f/" + 2.8,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 1600 + " s",
        focal_length: fixedData.focal_length + 4.3 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1vpPZQGwVgRtxRuXZePvmxGHZuAf3Lx8g",
        thumbnail: fixedData.url + "1HL7kyvPTNvMJQlvpEteaImOG9iGy3H3x",
        author: fixedData.author,
        name: "Visage décoratif I",
        place: "Liège, " + fixedData.belgium,
        day: "Dimanche",
        date: 7 + " août " + 2016,
        time: "16:14",
        aperture: fixedData.aperture + "f/" + 3.2,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 640 + " s",
        focal_length: fixedData.focal_length + 6.9 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1Sbx_Q_O2-keM5MfsL4KW5oWAawvUaNSG",
        thumbnail: fixedData.url + "1tDRGzy3t62j05EO7_Lt1TfdOpZrEpsvi",
        author: fixedData.author,
        name: "Visage décoratif II",
        place: "Liège, " + fixedData.belgium,
        day: "Dimanche",
        date: 7 + " août " + 2016,
        time: "16:16",
        aperture: fixedData.aperture + "f/" + 3.2,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 500 + " s",
        focal_length: fixedData.focal_length + 6.9 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1AZQa35ofCxjjq5cm3sncpb2q4GuEF-Eh",
        thumbnail: fixedData.url + "1mNFPMDOJhMc9vLqzyoT-fIvQ9FzFbYQq",
        author: fixedData.author,
        name: "Le Grand Curtius",
        place: "Liège, " + fixedData.belgium,
        day: "Dimanche",
        date: 7 + " août " + 2016,
        time: "18:33",
        aperture: fixedData.aperture + "f/" + 8.0,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 60 + " s",
        focal_length: fixedData.focal_length + 15.1 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1M_rtPwGQlKbD_o6-NTCX1Rm3oiIuyJeZ",
        thumbnail: fixedData.url + "1_tDXHCM_bhAN9eQBcrkcxHVEN8Ct7XGA",
        author: fixedData.author,
        name: "Le Tapis de fleur à l'heure japonaise",
        place: "Bruxelles, " + fixedData.belgium,
        day: "Samedi",
        date: 13 + " août " + 2016,
        time: "15:03",
        aperture: fixedData.aperture + "f/" + 8.0,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 160 + " s",
        focal_length: fixedData.focal_length + 12.6 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1gDvkgeBcGs940jZuGjAjmlnom2vHVDjT",
        thumbnail: fixedData.url + "1IiLBIQ_aSRbWt3A01q-cDYNIpVVcNLez",
        author: fixedData.author,
        name: "A travers le grillage",
        place: "Liège, " + fixedData.belgium,
        day: "Mercredi",
        date: 14 + " septembre " + 2016,
        time: "19:52",
        aperture: fixedData.aperture + "f/" + 8.0,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 15 + " s",
        focal_length: fixedData.focal_length + 33.4 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1QB6l-P0lGMG-M4pqivXqcwd56Ouu8-v4",
        thumbnail: fixedData.url + "1ZIDYBEszy9_66J19UADBNJczMA8-S_JF",
        author: fixedData.author,
        name: "Arcs en ciel",
        place: "Liège, " + fixedData.belgium,
        day: "Samedi",
        date: 24 + " septembre " + 2016,
        time: "15:23",
        aperture: fixedData.aperture + "f/" + 8.0,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 100 + " s",
        focal_length: fixedData.focal_length + 4.3 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1UUpNP_K5cPGAslaac_tcRCsQchYd2_No",
        thumbnail: fixedData.url + "14BrcjP1PsxaqO9WKgUnCDcCnoSnz-Q3v",
        author: fixedData.author,
        name: "Indice du temps I",
        place: "Liège, " + fixedData.belgium,
        day: "Samedi",
        date: 24 + " septembre " + 2016,
        time: "15:49",
        aperture: fixedData.aperture + "f/" + 3.5,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 640 + " s",
        focal_length: fixedData.focal_length + 13.4 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1vnDf03ufwGGgu4qpxhJX4zPnPtgABedY",
        thumbnail: fixedData.url + "1KcePquLgJjOZGXU8mS3Edy-IiMEzk5yA",
        author: fixedData.author,
        name: "Attachement",
        place: "Liège, " + fixedData.belgium,
        day: "Mercredi",
        date: 5 + " octobre " + 2016,
        time: "16:42",
        aperture: fixedData.aperture + "f/" + 4.5,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 500 + " s",
        focal_length: fixedData.focal_length + 23.2 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1Wfx80akbZD3xfKrTj97wF3ZNsstOQ673",
        thumbnail: fixedData.url + "1n3pPxBb7JY98vAEGO_B_5fP3G5201Aa6",
        author: fixedData.author,
        name: "L'heure des trains",
        place: "Liège, " + fixedData.belgium,
        day: "Samedi",
        date: 15 + " octobre " + 2016,
        time: "17:13",
        aperture: fixedData.aperture + "f/" + 4.0,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 160 + " s",
        focal_length: fixedData.focal_length + 20.7 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "11_GU3HOD_2iJzztS9Z2v4vWMh-MSz-7q",
        thumbnail: fixedData.url + "1v5le6CElji82uG6F92gve_Qn7SDlxfTx",
        author: fixedData.author,
        name: "Indice du temps II",
        place: "Liège, " + fixedData.belgium,
        day: "Jeudi",
        date: 27 + " octobre " + 2016,
        time: "17:21",
        aperture: fixedData.aperture + "f/" + 2.8,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 100 + " s",
        focal_length: fixedData.focal_length + 4.3 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1NJbkAWFK2-2o_Dd-LB06-cu3E45J4LSK",
        thumbnail: fixedData.url + "1wjgqr5dznFy0ny07fsI5M_R-XEHoMMDV",
        author: fixedData.author,
        name: "Herbes glacées",
        place: "Liège, " + fixedData.belgium,
        day: "Jeudi",
        date: 29 + " décembre " + 2016,
        time: "15:31",
        aperture: fixedData.aperture + "f/" + 4.0,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 100 + " s",
        focal_length: fixedData.focal_length + 15.6 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    }
];

const photos2017 =
[
    {
        title: 2017
    },
    {
        full_image: fixedData.url + "1TZ9V1cO1fyg3s_Uh6CL9L6lSj-r11Oty",
        thumbnail: fixedData.url + "1UplsD-lSVjuKkCJ126wjINBWnEPrDb-W",
        author: fixedData.author,
        name: "Ombre agitée",
        place: "Liège, " + fixedData.belgium,
        day: "Jeudi",
        date: 5 + " janvier " + 2017,
        time: "18:12",
        aperture: fixedData.aperture + "f/" + 4.0,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 20 + " s",
        focal_length: fixedData.focal_length + 17.3 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "13gXI-pvtb2XVK6digrdU3mwooi9S_QfP",
        thumbnail: fixedData.url + "1kWmgs7_77afPveLe55wtzh0TghxPO3xZ",
        author: fixedData.author,
        name: "Epines",
        place: "Liège, " + fixedData.belgium,
        day: "Vendredi",
        date: 13 + " janvier " + 2017,
        time: "16:30",
        aperture: fixedData.aperture + "f/" + 4.5,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 25 + " s",
        focal_length: fixedData.focal_length + 22.3 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1dPpT4aeKOvMGHMzUc7ORpxFiWPwt9X_F",
        thumbnail: fixedData.url + "1kRe0kRuwsRhaTkwokuLDXVY9i4AVHYCJ",
        author: fixedData.author,
        name: "Le maillon",
        place: "Liège, " + fixedData.belgium,
        day: "Dimanche",
        date: 29 + " janvier " + 2017,
        time: "16:31",
        aperture: fixedData.aperture + "f/" + 3.5,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 500 + " s",
        focal_length: fixedData.focal_length + 8.4 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "11cyHdD61vAe6aQZev7wTBlFXIufWMf9z",
        thumbnail: fixedData.url + "1yfxNV0_LPpp46Pge08hh3RqhnTpV78U1",
        author: fixedData.author,
        name: "Cœur d'orchidée",
        place: "Liège, " + fixedData.belgium,
        day: "Samedi",
        date: 11 + " février " + 2017,
        time: "16:11",
        aperture: fixedData.aperture + "f/" + 3.5,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 20 + " s",
        focal_length: fixedData.focal_length + 10.3 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1EYaLizDJA5EKQJCNeUocP24xeuXFvQNN",
        thumbnail: fixedData.url + "1QT2F5o0D0i2TmZUJ-Fz9SRxc1gntSCnu",
        author: fixedData.author,
        name: "Majestueux",
        place: "Liège, " + fixedData.belgium,
        day: "Dimanche",
        date: 12 + " mars " + 2017,
        time: "16:12",
        aperture: fixedData.aperture + "f/" + 5.0,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 125 + " s",
        focal_length: fixedData.focal_length + 30.7 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    }
];

const photos2018 =
[
    {
        title: 2018
    },
    {
        full_image: fixedData.url + "10zkXaQHZDMY22MkBA_Xw4wrK8gP1wFM4",
        thumbnail: fixedData.url + "14_2JeZ5CNmIUpqA8XRGPM3oph9uNr_dn",
        author: fixedData.author,
        name: "Liège Together",
        place: "Liège, " + fixedData.belgium,
        day: "Samedi",
        date: 23 + " juin " + 2018,
        time: "14:31",
        aperture: fixedData.aperture + "f/" + 2.8,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 640 + " s",
        focal_length: fixedData.focal_length + 4.8 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1iKC8r7_UYiLFeXCbtVD8YfawjOrBocLP",
        thumbnail: fixedData.url + "1kAId_sRUW8FXl3xARXL7w0fpG07x-qC0",
        author: fixedData.author,
        name: "S'en dessus-dessous",
        place: "Liège, " + fixedData.belgium,
        day: "Mercredi",
        date: 4 + " juillet " + 2018,
        time: "15:18",
        aperture: fixedData.aperture + "f/" + 2.8,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 125 + " s",
        focal_length: fixedData.focal_length + 4.3 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1lvX1OmeXyS8fpSkGJbLgW39MT24BsQuX",
        thumbnail: fixedData.url + "1_eRZnEN6VqaP2FkRp6lrTLdcIk9LmNDk",
        author: fixedData.author,
        name: "Le Parc d'Avroy",
        place: "Liège, " + fixedData.belgium,
        day: "Vendredi",
        date: 13 + " juillet " + 2018,
        time: "16:20",
        aperture: fixedData.aperture + "f/" + 3.5,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 320 + " s",
        focal_length: fixedData.focal_length + 11.2 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1EFxQcwkBeAngyumU2KxyetutkswVs94n",
        thumbnail: fixedData.url + "1w6EDwTiyfXDBRbuOVZ-RnTGZxCWpQ-BF",
        author: fixedData.author,
        name: "Le Palais Provincial",
        place: "Liège, " + fixedData.belgium,
        day: "Mercredi",
        date: 18 + " juillet " + 2018,
        time: "16:15",
        aperture: fixedData.aperture + "f/" + 3.2,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 1250 + " s",
        focal_length: fixedData.focal_length + 6.8 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1FIBxzjelZSB55OCiljUWIk_HSwI7X1oq",
        thumbnail: fixedData.url + "1jaLM31Ghy4CrVexYjpya8qlEGzF7DAph",
        author: fixedData.author,
        name: "La lumière dans l'obscurité",
        place: "Liège, " + fixedData.belgium,
        day: "Mercredi",
        date: 18 + " juillet " + 2018,
        time: "16:27",
        aperture: fixedData.aperture + "f/" + 5.6,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 500 + " s",
        focal_length: fixedData.focal_length + 74.2 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1sfWbGlqnCcTtMWPBRy_bOFPI6Gw6Pr8D",
        thumbnail: fixedData.url + "1sBvLl1qAlOYsGlU71u8g83fUO0hDqi2R",
        author: fixedData.author,
        name: "Rose éclatante",
        place: "Liège, " + fixedData.belgium,
        day: "Samedi",
        date: 11 + " août " + 2018,
        time: "14:24",
        aperture: fixedData.aperture + "f/" + 5.6,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 500 + " s",
        focal_length: fixedData.focal_length + 74.2 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1rgG3a_JhGlNyEuOl1ZWpPrAp0-QztN-N",
        thumbnail: fixedData.url + "18SdT_rWDKSngG4e48lhEXvIavD3EdE26",
        author: fixedData.author,
        name: "Insouciance",
        place: "Liège, " + fixedData.belgium,
        day: "Dimanche",
        date: 12 + " août " + 2018,
        time: "15:56",
        aperture: fixedData.aperture + "f/" + 5.6,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 160 + " s",
        focal_length: fixedData.focal_length + 116.8 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1-Jre6rwu1Zr-MYAz4KUlMnypphL79OVu",
        thumbnail: fixedData.url + "1Rmkq5W-lgmiggOD0Q9njUCqx4UL6gXBP",
        author: fixedData.author,
        name: "Nuances de vert",
        place: "Liège, " + fixedData.belgium,
        day: "Mercredi",
        date: 15 + " août " + 2018,
        time: "15:04",
        aperture: fixedData.aperture + "f/" + 5.0,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 30 + " s",
        focal_length: fixedData.focal_length + 51.1 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "11hLucnfpLV304PkEZnpq-w3BOFNQk4Jm",
        thumbnail: fixedData.url + "1PHVbAZqLgdxPNz4lihAbOClmQMoxCpSN",
        author: fixedData.author,
        name: "L'observatoire de Cointe",
        place: "Liège, " + fixedData.belgium,
        day: "Jeudi",
        date: 16 + " août " + 2018,
        time: "12:21",
        aperture: fixedData.aperture + "f/" + 8.0,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 160 + " s",
        focal_length: fixedData.focal_length + 6.9 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1zUxiM_k68FcKbP2giMlLgWKned_xIYNd",
        thumbnail: fixedData.url + "10yDFIvmFTLkNc5H2Ygw4b1zyP2QlI_3F",
        author: fixedData.author,
        name: "Quai d'Outremeuse",
        place: "Liège, " + fixedData.belgium,
        day: "Jeudi",
        date: 16 + " août " + 2018,
        time: "13:19",
        aperture: fixedData.aperture + "f/" + 3.5,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 800 + " s",
        focal_length: fixedData.focal_length + 11.9 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1GTaLi4Dg8_m6Nj88WqAvfyUNcprq-mwN",
        thumbnail: fixedData.url + "14IQXQ59YR4_2jct-kmKK3RsE-C9JoDq6",
        author: fixedData.author,
        name: "Buddleia sauvage",
        place: "Liège, " + fixedData.belgium,
        day: "Jeudi",
        date: 16 + " août " + 2018,
        time: "14:19",
        aperture: fixedData.aperture + "f/" + 3.5,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 800 + " s",
        focal_length: fixedData.focal_length + 9.8 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1G30dFQ08efzxxnWvOeaeB3t8iouJs-KY",
        thumbnail: fixedData.url + "1Q95Y_Tq9182_pt01Mjuz8DGK5SQAMzkY",
        author: fixedData.author,
        name: "Lune",
        place: "Liège, " + fixedData.belgium,
        day: "Vendredi",
        date: 28 + " septembre " + 2018,
        time: "22:14",
        aperture: fixedData.aperture + "f/" + 6.3,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 80 + " s",
        focal_length: fixedData.focal_length + 215.0 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    }
];

const photos2019 =
[
    {
        title: 2019
    },
    {
        full_image: fixedData.url + "1jPOLj2O9n7iG5-YGMSRRNC3gj1T-AaZx",
        thumbnail: fixedData.url + "1X_cL_IzABX9I_DuEOv33yWR4e04JnYr5",
        author: fixedData.author,
        name: "Cœur de tulipe",
        place: "Liège, " + fixedData.belgium,
        day: "Vendredi",
        date: 29 + " mars " + 2019,
        time: "17:04",
        aperture: fixedData.aperture + "f/" + 2.8,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 100 + " s",
        focal_length: fixedData.focal_length + 5.5 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1oPdyA292zgTbnYEFv7dmsfpSlDEHZb9T",
        thumbnail: fixedData.url + "1NjPhLjdGmmdFiyfgY2tp5TDg_b8Nh2Yp",
        author: fixedData.author,
        name: "La Tour des Vieux-Joncs",
        place: "Liège, " + fixedData.belgium,
        day: "Jeudi",
        date: 18 + " avril " + 2019,
        time: "14:47",
        aperture: fixedData.aperture + "f/" + 2.8,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 2000 + " s",
        focal_length: fixedData.focal_length + 4.3 + " mm",
        iso: fixedData.iso + 100,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1PopzrOuF_aWSzfaaI1sOKfKL7jKRVNgN",
        thumbnail: fixedData.url + "1-ecgMN6jW7acjt3HUGAZfJ1ca80K4mlS",
        author: fixedData.author,
        name: "Repos dans l'herbe",
        place: "Liège, " + fixedData.belgium,
        day: "Mercredi",
        date: "1er" + " mai " + 2019,
        time: "16:09",
        aperture: fixedData.aperture + "f/" + 5.6,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 250 + " s",
        focal_length: fixedData.focal_length + 157.4 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1wWkP9oehHTa7BciFo7qHGeLzjhy0M6Xv",
        thumbnail: fixedData.url + "1sCdx7rTuizbz3OqVuGaaWRtvQ-5ozXiM",
        author: fixedData.author,
        name: "Printemps ensoleillé",
        place: "Liège, " + fixedData.belgium,
        day: "Vendredi",
        date: 10 + " mai " + 2019,
        time: "16:47",
        aperture: fixedData.aperture + "f/" + 5.6,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 125 + " s",
        focal_length: fixedData.focal_length + 140.2 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1MXQDvYRDWSGggBklwDhfZWoDVd5elDsX",
        thumbnail: fixedData.url + "1OTVE8WqfzEk3dHi4WlK20FdL7UtMMuWD",
        author: fixedData.author,
        name: "L'envol de la Wallonie",
        place: "Liège, " + fixedData.belgium,
        day: "Vendredi",
        date: 10 + " mai " + 2019,
        time: "17:15",
        aperture: fixedData.aperture + "f/" + 8.0,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 100 + " s",
        focal_length: fixedData.focal_length + 6.1 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "12yo4zAbyZJAOasKgD6crFn0E9Lmo-0Og",
        thumbnail: fixedData.url + "1XkmYnFq1LmZUJ91pYf8JQ91LnV3rUfjl",
        author: fixedData.author,
        name: "Regard félin",
        place: "Liège, " + fixedData.belgium,
        day: "Vendredi",
        date: 10 + " mai " + 2019,
        time: "17:51",
        aperture: fixedData.aperture + "f/" + 4.5,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 8 + " s",
        focal_length: fixedData.focal_length + 34.8 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1bf7lWr6afH0rE5KmmsrTD6c-JIaSmmja",
        thumbnail: fixedData.url + "1NgePFxIQrS2UxJ-YglKJKBlxLqoqNMG_",
        author: fixedData.author,
        name: "Ornements I",
        place: "Bruxelles, " + fixedData.belgium,
        day: "Samedi",
        date: 18 + " mai " + 2019,
        time: "11:39",
        aperture: fixedData.aperture + "f/" + 4.5,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 125 + " s",
        focal_length: fixedData.focal_length + 33.4 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "18VRMENAMVnrDgs1XzvPv0YJqoXYoX3Be",
        thumbnail: fixedData.url + "1PtUuF0mYZSSuRa9qBFOiqJAlHBrLUMXn",
        author: fixedData.author,
        name: "Ornements II",
        place: "Bruxelles, " + fixedData.belgium,
        day: "Samedi",
        date: 18 + " mai " + 2019,
        time: "11:40",
        aperture: fixedData.aperture + "f/" + 4.5,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 400 + " s",
        focal_length: fixedData.focal_length + 32.0 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1XpuGx3W_EaiA50ejvml5GBI0DNO69BkJ",
        thumbnail: fixedData.url + "16BplHGokH31V9lHvTGA5CsZseAVeT1ax",
        author: fixedData.author,
        name: "Ornements III",
        place: "Bruxelles, " + fixedData.belgium,
        day: "Samedi",
        date: 18 + " mai " + 2019,
        time: "11:42",
        aperture: fixedData.aperture + "f/" + 5.0,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 320 + " s",
        focal_length: fixedData.focal_length + 49.0 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1CrKYRIaoe-zSbJoZR7uMhmuC6TmRwQ-V",
        thumbnail: fixedData.url + "1Crm7xKhuP1uE6Aj1205GDmW_iNqmpLDh",
        author: fixedData.author,
        name: "Ornements IV",
        place: "Bruxelles, " + fixedData.belgium,
        day: "Samedi",
        date: 18 + " mai " + 2019,
        time: "11:43",
        aperture: fixedData.aperture + "f/" + 5.0,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 320 + " s",
        focal_length: fixedData.focal_length + 55.6 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1St-fou8NnksISYwmVs4RMPXe20CknbfI",
        thumbnail: fixedData.url + "11MWLOWbvi50sFHXUCPGFuTx-B2mopzTn",
        author: fixedData.author,
        name: "Ornements V",
        place: "Bruxelles, " + fixedData.belgium,
        day: "Samedi",
        date: 18 + " mai " + 2019,
        time: "11:45",
        aperture: fixedData.aperture + "f/" + 4.5,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 500 + " s",
        focal_length: fixedData.focal_length + 29.4 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "1GZ2bp6J9ccbtbzhxvkwx0XdD91d1yFwl",
        thumbnail: fixedData.url + "1_vIFz1pPgqKu_al48D5OmrSXnYLOp6KP",
        author: fixedData.author,
        name: "Monument au 14ème Régiment de Ligne",
        place: "Liège, " + fixedData.belgium,
        day: "Samedi",
        date: 22 + " juin " + 2019,
        time: "14:07",
        aperture: fixedData.aperture + "f/" + 8.0,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 320 + " s",
        focal_length: fixedData.focal_length + 4.3 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    },
    {
        full_image: fixedData.url + "16L4UzcLEFB_Xc_5IMes0eQ53IL-VsCfl",
        thumbnail: fixedData.url + "1C2QiiMuZNUtPEtIkLHPQu_eZjUSwoRZB",
        author: fixedData.author,
        name: "Rivière dans la cour",
        place: "Liège, " + fixedData.belgium,
        day: "Dimanche",
        date: 21 + " juillet " + 2019,
        time: "14:21",
        aperture: fixedData.aperture + "f/" + 3.2,
        shutter_speed: fixedData.shutter_speed + 1 + "/" + 400 + " s",
        focal_length: fixedData.focal_length + 6.8 + " mm",
        iso: fixedData.iso + 80,
        camera: fixedData.camera
    }
];

const photos2020 =
[
    {
        title: 2020
    }
];

export {photos2014, photos2015, photos2016, photos2017, photos2018, photos2019, photos2020};